### ISSUE TITLE
Voice notes not playing on Telegram for iOS/macOS

### ISSUE THREAD

**Issue by Dabolus** [FiorixF1/fioriktos-bot#4]
When using the Telegram app for iOS and macOS, the voice notes sent by the bot cannot be played. I also noticed that the length of the voice notes is always displayed as `00:00` on any Telegram app, so there might be an issue with how the voice notes files are generated.

**Comment by FiorixF1** [comment]
Hello,

Thank you for reporting, since I don't have an iOS device to test. I think it is fixed now in 062bc32.

**Comment by Dabolus** [comment]
Yes, it now works on both iOS and macOS and the audio length is displayed correctly, thanks!
