### ISSUE TITLE
Fioriktos resets after about 1 hour

### ISSUE THREAD

**Issue by Trial4life** [FiorixF1/fioriktos-bot#6]
I'm in a telegram group of 3 users + Fioriktos bot. The group was converted to supergroup a couple of hours ago. Every hour Fioriktos completely resets (torrent value returns to 5, and all of the words are deleted). The same thing was happening to the same group even before converting it into supergroup.

How can I fix this issue?

**Comment by Eklip5e** [comment]
I have the same problem, but that happened way before, almost a month ago we started a group (67 people + 2 bots, Fioriktos is one of them) the words got deleted at first after a week and then even after less time: 5 days, then 2 hours.
Please fix it, i love so much use that bot!!

**Comment by FiorixF1** [comment]
Commit 2deb107dbb1231656aa709e19e9b550685cbb766 probably fixes this issue.

**Comment by Trial4life** [comment]
> Commit [2deb107](https://github.com/FiorixF1/fioriktos-bot/commit/2deb107dbb1231656aa709e19e9b550685cbb766) probably fixes this issue.

Many thanks for the reply. Do you know what was causing the issue? Because in some groups it is working flawlessly, while in other groups it keeps resetting again and again...

**Comment by FiorixF1** [comment]
It is expected that, under heavy load, the bot can reboot and lose memory of the data learnt in the last half an hour if they have not been synchronized on the DB. However it is not expected to erase an entire chat. I found a bug in the synchronization logic with the DB that most likely caused the issue.

**Comment by Eklip5e** [comment]
is there a way to host the same bot (api, credits) on another machine? just to save fioriktos's dictionary and avoid the bot resetting?

**Comment by FiorixF1** [comment]
Yes, just follow the instructions in the Readme and run /gdpr download to get the dictionary.

However I am going to host the bot on some other service since Heroku will drop the free tier in November. This will bring some modifications in the code.
